version: '3.8'

services:
  ccaffa-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccaffa-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://carflej.com.ar:3306/carflejc_demo_ccaffa
      - SPRING_DATASOURCE_USERNAME=carflejc_desarrolladores
      - SPRING_DATASOURCE_PASSWORD=proyectofinal
      - JWT_SECRET=ccaffaSecretKey1234567890123456789012345678901234567890
      - JWT_EXPIRATION=18000
      - GRPC_CLIENT_IMAGE_CLASSIFIER_ADDRESS=static://host.docker.internal:50051
      - FILE_STORAGE_PATH=/app/storage/images
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    networks:
      - ccaffa-network

networks:
  ccaffa-network:
    driver: bridge
